### ISSUE TITLE
Team Formatting

### ISSUE THREAD

**Issue by GMeulendyks** [daltonpearson/Scripts#1]
The team formatting is a bit confusing for end users. I'd suggest a layout similar to this:

Team 1:
    "Top:" foo
    "Bot:" bar
    ....

Team 2:
    "Top:" foo
    "Bot:" bar

Would really appreciate this.

**Comment by GMeulendyks** [comment]
@daltonpearson What's the status on this?

**Comment by daltonpearson** [comment]
Fixed in commit: https://github.com/daltonpearson/Scripts/commit/afa894ca146c658cbbadbbc375c6baaa0baaea9d

**Comment by GMeulendyks** [comment]
10/10 code. Would recommend.
